Client/desktop windows
VIAME/VIAME-Web pull request #481
Opened 2020-12-07 16:26 UTC by BryonLewis

Fixes #466 

I have some other items I want to test/fix before a PR.  I'm going to use this issue as a log to help organize stuff (warning you if you want to unsubscribe, so you don't get continuous warnings.)

Need to figure out what is going on between GPU and CPU versions.  Same executable with the same source file running the the `generic_object_proposal`s pipeline on two different machines with different versions of VIAME (CPU only, vs GPU version) behaves differently.

- The CPU only on laptop takes like 5 minutes on the source data and provides relevant results.
- The GPU version of VIAME on a more powerful desktop started and ran for 20+ minutes (stopped before allowing it to continue).

Testing parameters to determine the problem:
- Get the command from the log manually and run it.  I want to make sure it isn't something in the way the command was built.
- Install the CPU only version on the desktop and run it to determine if it is an issue with how the GPU one is configured or setup.

List of other TODOs before creating PR:

- [ ] Ensure the %PROGRAMFILES% code works properly, and that executes before the confirmation of Kwiver install
- [ ] Add in a loading spinner or something to the testing of the kwiver install and GPU.  They take long enough (2-4 seconds) that we need an indication that something is attempting to verify when the user clicks save or navigates to the page.
- [ ] At least look into application signing (low priority).  Windows continually gives the "WARNING THIS SOFTWARE IS UNVERIFIED" stuff when running the electron version for the first time.
- [ ] Check symlinks and how they behave when using shortcuts for the data
- [ ] On windows nvidia-smi.exe isn't global and could be in a different location depending on where they install their drivers.  May want to give a clarification that just because a GPU couldn't be found doesn't mean that it won't work.
- [ ] Text log for the jobs panel.  Need to look into getting it to both write to the runlog.txt and the jobs display at the same time.  Right now I have it only writing to the runlog.txt file.

2020-12-08 14:41 UTC, BryonLewis commented
Did some testing last night.  The Desktop PC with the graphics card would run the CPU only version perfectly fine.  When using the GPU version I can see that the GPU is consuming memory (~ 2X 250MB which goes up to about 2X 1GB after a little while) but the process doesn't complete within 20-30 minutes.  I think we may need some clarity on the detectors that are enabled.

2020-12-10 13:53 UTC, subdavis requested changes
Only real requested change is the `nvidia-smi` one.  Others are all optional.

2020-12-10 13:53 UTC, subdavis commented on client/platform/desktop/backend/ipcService.ts
> +import OS from 'os';
language imports should go above external imports.

Need to find the linter settings for that...

2020-12-10 13:53 UTC, subdavis commented on client/platform/desktop/backend/ipcService.ts
> +  // it could be on another drive letter
```suggestion
```

Remove or move to windows file.  Generally, document implementation details inside the function instead of at the caller.

2020-12-10 13:53 UTC, subdavis commented on client/platform/desktop/backend/platforms/windows.ts
> +import { xml2json } from 'xml-js';
```suggestion
import npath from 'path';
import { spawn } from 'child_process';
import { app } from 'electron';
import fs from 'fs-extra';
import { xml2json } from 'xml-js';
```

Reorder imports.

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

2020-12-10 13:53 UTC, subdavis commented on client/platform/desktop/backend/platforms/windows.ts
> +    const smi = spawn(`"${programFiles}\\NVIDIA Corporation\\NVSMI\\nvidia-smi.exe"`, ['-q', '-x'], { shell: true });
According to https://stackoverflow.com/questions/57100015/how-do-i-run-nvidia-smi-on-windows that is an outdated location.

Newer installs apparently put `nvidia-smi` on `PATH`.  Could we try an option where we `os.stat` the old location, then attempt to run `nvidia-smi` as defined by `PATH`?

2020-12-10 14:15 UTC, BryonLewis commented on client/platform/desktop/backend/platforms/windows.ts
> +    const smi = spawn(`"${programFiles}\\NVIDIA Corporation\\NVSMI\\nvidia-smi.exe"`, ['-q', '-x'], { shell: true });
I saw that same issue and I looked to see if I could run it.  I went to media PC which I just reinstalled windows on yesterday  and the graphic drivers.  `nvidia-smi.exe` is not accessible from the cmd.exe by default and it's not located on the path either.  It doesn't hurt to check multiple locations and I can add that in.

![image](https://user-images.githubusercontent.com/61746913/101781547-f519a900-3ac5-11eb-9e77-803e998017d3.png)

nvidia-smi.exe is in my C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7ad69efe14475762 which is very different than the stack overflow and I feel is dependent on the individual card and the users other system configuration.  It also may be that quadro cards install nvidia-smi into a different location than geforce cards do.  I'll do a bit more research into seeing if there is a difference between quadro and geforce cards.  I don't know how we could guarantee where in the FileRepository it is located unless we do a search on every folder (~1000 folders),

2020-12-10 14:18 UTC, subdavis commented on client/platform/desktop/backend/platforms/windows.ts
> +    const smi = spawn(`"${programFiles}\\NVIDIA Corporation\\NVSMI\\nvidia-smi.exe"`, ['-q', '-x'], { shell: true });
Well if that SO answer is just wrong, I'm fine with this change.  I agree we shouldn't be doing directory searches or anything like that. 

Since this isn't an easy change, let's just merge it as-is.

2020-12-10 16:37 UTC, BryonLewis commented on client/platform/desktop/backend/platforms/windows.ts
> +    const smi = spawn(`"${programFiles}\\NVIDIA Corporation\\NVSMI\\nvidia-smi.exe"`, ['-q', '-x'], { shell: true });
I modified it so that it will test for the Path location first and then if that fails over it will test for the C:\Program Files\NVSMI location.  I tested it my manually manipulating the location of the file.  My guess is that if you install any tools for development purposes that it will place nvidia-smi.exe into the path and that any subsequent driver updates will see that and prevent it from going in the Program Files directory.

My recently formatted media PC had it located in C:\Program Files.
My desktop old dev PC (which had some stuff for Unity and other Nvidia dev stuff) had it in the Path, even after I updated to the same drivers as my media PC.
I tested on the desktop PC, by manually moving the nvidia-smi.exe from the path in Windows/System 32 to Program Files and this new update will work with both.

There may be a cleaner structure than what I did and I'll solicit your opinion for that.

2020-12-10 16:38 UTC, subdavis approved these changes

2020-12-10 16:50 UTC, merged