Format text custom function
VIAME/VIAME-Web pull request #489
Opened 2020-12-11 20:21 UTC by subdavis

For @zachmullen

2020-12-11 20:37 UTC, BryonLewis commented
is this still too locked down?  Should you be able to edit the styling at the same time if you want to edit the text?  Text size, color and other options are still dependent on the type specified.  I don't know the immediacy of this or the intended usage, but just wondering if we should give some more control besides just formatting the TextData output.

2020-12-11 20:40 UTC, subdavis commented
> text size, color and other options are still dependent on the type specified

You'd have to "coordinate" with the typeStyling properties, which I think is reasonable given that's how everything else works.

This is already much more than Zach needs, so I'm reluctant to go out of my way to make this ultra-flexible without a use case. This was just the most convenient way to expose the functions he needed.

2020-12-11 21:00 UTC, BryonLewis requested changes
Testing worked well.

I'm open to any ideas you may have about multiple text items per FrameDataTrack.  I just don't want to have to break or change this functionality afterwards to solve a VIAME issue.

2020-12-14 15:15 UTC, subdavis commented on client/src/layers/TextLayer.ts
> +function defaultFormatter(track: FrameDataTrack): TextData | null {
I looked at your changes from your other open PR, and returning an array here is perfectly fine with me.

64bc004

2020-12-14 16:09 UTC, BryonLewis approved these changes

2020-12-14 16:17 UTC, merged