Zoom #491
VIAME/VIAME-Web pull request #498
Opened 2020-12-14 16:59 UTC by subdavis

fixes #491 #492 #496

2020-12-14 17:07 UTC, subdavis commented on client/src/components/annotators/useMediaController.ts
> +      min: -Infinity,
This seems to have the desired effect: always make min zoom the size of the map.

I can't figure out _why_ it does this, but I figured @BryonLewis will know.

2020-12-15 13:15 UTC, BryonLewis commented
Closing because this was mainly for ease of demonstration.

2020-12-15 13:17 UTC, subdavis commented
This is my PR, not yours :P

2020-12-15 18:56 UTC, subdavis commented
Fixed.  I had a dumb math problem.  zero identity is hard.

2020-12-15 19:44 UTC, BryonLewis requested changes
Just the DIVE question.

Noting this in case we ever have to come back to this:
Just noting that the caveat with 4x zoom level is that the most you will get for zooming in pixel resizing is (dimension*2^4) so a 256x256 image would become 4096x4096  which should be sufficient in most cases (I don't think anyone out there has an 8K monitor/TV they are using this on).  This is separate from window resizing though, that can cause you to have a zoom level outside of the clamped min/max levels.  I don't think we need to adjust this now, but just noting for eventual searching if we have to address this again.

2020-12-15 19:44 UTC, BryonLewis commented on client/platform/desktop/components/Recent.vue
> +              Dive Annotation Tool
Terribly sorry, should this be 'DIVE' now?

2020-12-15 20:02 UTC, subdavis commented
Changed it in the electron build config as well.

2020-12-15 20:15 UTC, BryonLewis approved these changes
Looks good

2020-12-15 20:54 UTC, merged